
import React, { useState } from 'react';
import { geminiService } from '../../services/geminiService';
import { GenAITool } from '../../types';
import { Copy, Wand2, Image as ImageIcon, Mic, Play, Square, Volume2, Briefcase, ShoppingBag, Zap, Feather, ScanEye, Layers, AlertCircle, CheckCircle2, Download, Settings2, FilePen, Sparkles, ArrowRight, BrainCircuit, RefreshCw, Send, Smartphone, Hash } from 'lucide-react';

const GenAIStudio: React.FC = () => {
  const [activeTool, setActiveTool] = useState<GenAITool>(GenAITool.Copywriter);
  
  // Community Manager States
  const [platform, setPlatform] = useState('Instagram');
  const [tone, setTone] = useState('Disruptivo');
  const [topicInput, setTopicInput] = useState('');
  
  // The Strategy State (Text + Image Prompt)
  const [socialStrategy, setSocialStrategy] = useState<{copy: string, hashtags: string, visual_prompt: string} | null>(null);
  const [isGeneratingStrategy, setIsGeneratingStrategy] = useState(false);
  
  // The Final Result State
  const [socialImage, setSocialImage] = useState<string | null>(null);
  const [isGeneratingSocialImage, setIsGeneratingSocialImage] = useState(false);

  // Smart Editor States
  const [editorInput, setEditorInput] = useState('');
  const [editorOutput, setEditorOutput] = useState('');
  const [isEditing, setIsEditing] = useState(false);

  // Image Tool States (Standalone)
  const [imagePrompt, setImagePrompt] = useState('');
  const [imageStyle, setImageStyle] = useState('Cinemático');
  const [enhancedPrompt, setEnhancedPrompt] = useState('');
  const [promptAnalysis, setPromptAnalysis] = useState<any>(null);
  
  const [aspectRatio, setAspectRatio] = useState('1:1');
  const [imageSize, setImageSize] = useState('1K');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  
  // Voice states
  const [textToSpeechInput, setTextToSpeechInput] = useState('');
  const [isSpeaking, setIsSpeaking] = useState(false);

  // --- Community Manager Logic ---

  const generateSocialStrategy = async () => {
      setIsGeneratingStrategy(true);
      setSocialStrategy(null);
      setSocialImage(null);
      
      const result = await geminiService.generateSocialCampaign(topicInput, platform, tone);
      setSocialStrategy(result);
      
      setIsGeneratingStrategy(false);
  };

  const executeVisualProduction = async () => {
      if (!socialStrategy) return;
      
      // Check for API Key for Nano Banana Pro
      if ((window as any).aistudio && !await (window as any).aistudio.hasSelectedApiKey()) {
          await (window as any).aistudio.openSelectKey();
      }

      setIsGeneratingSocialImage(true);
      
      // We use the prompt generated by the previous step
      const imageBase64 = await geminiService.generateImage(socialStrategy.visual_prompt, '1:1', '1K');
      
      if (imageBase64) {
          setSocialImage(imageBase64);
      }
      setIsGeneratingSocialImage(false);
  };

  // --- Other Logic ---

  const handleSmartEdit = async (task: string, complexity: 'basic' | 'complex') => {
      if (!editorInput.trim()) return;
      
      if (complexity === 'complex' && (window as any).aistudio && !await (window as any).aistudio.hasSelectedApiKey()) {
          await (window as any).aistudio.openSelectKey();
      }

      setIsEditing(true);
      const result = await geminiService.editContent(editorInput, task, complexity);
      setEditorOutput(result);
      setIsEditing(false);
  };

  const enhancePrompt = async () => {
    setIsGenerating(true);
    setPromptAnalysis(null);
    setEnhancedPrompt('');
    
    // Use isGenerating state (reused logic for loading)
    const systemInstruction = `Eres un ingeniero de prompts experto en Midjourney v6. Tu trabajo es tomar una idea básica y convertirla en un prompt detallado, estilo ${imageStyle}, y fotorrealista en INGLÉS.`;
    
    const resultPromise = geminiService.generateText(
        `Mejora este concepto visual: ${imagePrompt}`,
        systemInstruction
    );

    const analysisPromise = geminiService.analyzeImagePrompt(imagePrompt);

    const [result, analysis] = await Promise.all([resultPromise, analysisPromise]);

    setEnhancedPrompt(result);
    setPromptAnalysis(analysis);
    setIsGenerating(false);
  };

  // State to simulate generic loading for standalone tool
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateImage = async () => {
    if ((window as any).aistudio && !await (window as any).aistudio.hasSelectedApiKey()) {
        await (window as any).aistudio.openSelectKey();
    }
    
    setIsGeneratingImage(true);
    setGeneratedImage(null);
    const promptToUse = enhancedPrompt || imagePrompt;
    const imageBase64 = await geminiService.generateImage(promptToUse, aspectRatio, imageSize);
    if (imageBase64) setGeneratedImage(imageBase64);
    setIsGeneratingImage(false);
  };

  const handleSpeak = (text: string) => {
      geminiService.speak(text);
      setIsSpeaking(true);
      setTimeout(() => setIsSpeaking(false), text.length * 100); 
  };

  const handleStopSpeak = () => {
      geminiService.stopSpeaking();
      setIsSpeaking(false);
  };

  return (
    <div className="h-full flex flex-col">
        <div className="grid md:grid-cols-12 gap-6 h-full">
          {/* Sidebar */}
          <div className="md:col-span-3 space-y-2 border-r border-white/5 pr-4">
            <button 
              onClick={() => setActiveTool(GenAITool.Copywriter)}
              className={`w-full text-left px-4 py-3 rounded-lg text-sm font-mono flex items-center gap-3 transition-all ${activeTool === GenAITool.Copywriter ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30' : 'hover:bg-white/5 text-gray-400'}`}
            >
              <Send size={16} /> Community AI
            </button>
            <button 
              onClick={() => setActiveTool(GenAITool.SmartEditor)}
              className={`w-full text-left px-4 py-3 rounded-lg text-sm font-mono flex items-center gap-3 transition-all ${activeTool === GenAITool.SmartEditor ? 'bg-green-500/20 text-green-400 border border-green-500/30' : 'hover:bg-white/5 text-gray-400'}`}
            >
              <FilePen size={16} /> Editor Inteligente
            </button>
            <button 
              onClick={() => setActiveTool(GenAITool.ImageSynth)}
              className={`w-full text-left px-4 py-3 rounded-lg text-sm font-mono flex items-center gap-3 transition-all ${activeTool === GenAITool.ImageSynth ? 'bg-purple-500/20 text-purple-400 border border-purple-500/30' : 'hover:bg-white/5 text-gray-400'}`}
            >
              <ImageIcon size={16} /> Sintetizador Visual
            </button>
            <button 
              onClick={() => setActiveTool(GenAITool.Voice)}
              className={`w-full text-left px-4 py-3 rounded-lg text-sm font-mono flex items-center gap-3 transition-all ${activeTool === GenAITool.Voice ? 'bg-pink-500/20 text-pink-400 border border-pink-500/30' : 'hover:bg-white/5 text-gray-400'}`}
            >
              <Mic size={16} /> Clonación de Voz
            </button>
          </div>

          {/* Content Area */}
          <div className="md:col-span-9 p-2 overflow-y-auto custom-scrollbar pr-2 h-[600px]">
            
            {/* Community Manager Tool */}
            {activeTool === GenAITool.Copywriter && (
              <div className="space-y-6 animate-in fade-in pb-12">
                <div className="flex flex-col md:flex-row justify-between items-start gap-4">
                    <div>
                        <h3 className="text-xl font-bold font-display text-cyan-400 mb-2">Community Manager AI</h3>
                        <p className="text-sm text-gray-400">Flujo completo: De idea creativa a post visual terminado.</p>
                    </div>
                </div>

                <div className="grid lg:grid-cols-2 gap-8">
                    {/* LEFT: Config & Strategy */}
                    <div className="space-y-6">
                        {/* 1. Briefing */}
                        <div className="bg-white/5 border border-white/10 rounded-xl p-4 space-y-4">
                            <div className="flex items-center gap-2 mb-2 border-b border-white/5 pb-2">
                                <span className="bg-cyan-500/20 text-cyan-400 w-6 h-6 flex items-center justify-center rounded-full text-xs font-bold">1</span>
                                <h4 className="text-sm font-bold text-white">Configurar Campaña</h4>
                            </div>
                            
                            <div className="grid grid-cols-2 gap-3">
                                <div className="space-y-1">
                                    <label className="text-[10px] uppercase text-gray-500 font-mono">Plataforma</label>
                                    <select 
                                        value={platform}
                                        onChange={(e) => setPlatform(e.target.value)}
                                        className="w-full bg-black/30 border border-white/10 rounded px-2 py-2 text-sm text-white outline-none focus:border-cyan-400"
                                    >
                                        <option value="Instagram">Instagram</option>
                                        <option value="LinkedIn">LinkedIn</option>
                                        <option value="Twitter">Twitter / X</option>
                                        <option value="Facebook">Facebook</option>
                                    </select>
                                </div>
                                <div className="space-y-1">
                                    <label className="text-[10px] uppercase text-gray-500 font-mono">Tono de Voz</label>
                                    <select 
                                        value={tone}
                                        onChange={(e) => setTone(e.target.value)}
                                        className="w-full bg-black/30 border border-white/10 rounded px-2 py-2 text-sm text-white outline-none focus:border-cyan-400"
                                    >
                                        <option value="Disruptivo">Disruptivo</option>
                                        <option value="Profesional">Profesional</option>
                                        <option value="Divertido">Divertido</option>
                                        <option value="Minimalista">Minimalista</option>
                                    </select>
                                </div>
                            </div>
                            
                            <div className="space-y-1">
                                <label className="text-[10px] uppercase text-gray-500 font-mono">Idea Creativa / Tema</label>
                                <textarea
                                    value={topicInput}
                                    onChange={(e) => setTopicInput(e.target.value)}
                                    placeholder="Ej. Lanzamiento de tenis urbanos con luces neón..."
                                    className="w-full h-20 bg-black/30 border border-white/10 rounded-lg p-3 text-white text-sm resize-none focus:border-cyan-400 outline-none"
                                />
                            </div>

                            <button 
                                onClick={generateSocialStrategy}
                                disabled={isGeneratingStrategy || !topicInput}
                                className="w-full py-3 bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 rounded-lg hover:bg-cyan-500/20 font-bold flex items-center justify-center gap-2 transition-all"
                            >
                                {isGeneratingStrategy ? <span className="animate-spin">⏳</span> : <BrainCircuit size={16} />}
                                Generar Estrategia
                            </button>
                        </div>

                        {/* 2. Review & Edit */}
                        {socialStrategy && (
                            <div className="bg-white/5 border border-white/10 rounded-xl p-4 space-y-4 animate-in fade-in slide-in-from-bottom-4">
                                <div className="flex items-center gap-2 mb-2 border-b border-white/5 pb-2">
                                    <span className="bg-purple-500/20 text-purple-400 w-6 h-6 flex items-center justify-center rounded-full text-xs font-bold">2</span>
                                    <h4 className="text-sm font-bold text-white">Nutrir la Idea</h4>
                                </div>

                                <div>
                                    <label className="text-[10px] uppercase text-gray-500 font-mono flex items-center gap-1"><FilePen size={10} /> Editar Copy</label>
                                    <textarea 
                                        value={socialStrategy.copy}
                                        onChange={(e) => setSocialStrategy({...socialStrategy, copy: e.target.value})}
                                        className="w-full h-24 bg-black/30 border border-white/10 rounded p-2 text-sm text-gray-300 resize-none focus:border-purple-400 outline-none"
                                    />
                                </div>

                                <div>
                                    <label className="text-[10px] uppercase text-gray-500 font-mono flex items-center gap-1"><ScanEye size={10} /> Prompt Visual (Auto-generado)</label>
                                    <textarea 
                                        value={socialStrategy.visual_prompt}
                                        onChange={(e) => setSocialStrategy({...socialStrategy, visual_prompt: e.target.value})}
                                        className="w-full h-20 bg-black/30 border border-white/10 rounded p-2 text-xs text-gray-400 resize-none focus:border-purple-400 outline-none font-mono"
                                    />
                                </div>

                                <button 
                                    onClick={executeVisualProduction}
                                    disabled={isGeneratingSocialImage}
                                    className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold flex items-center justify-center gap-2 hover:shadow-[0_0_20px_rgba(168,85,247,0.4)] transition-all"
                                >
                                    {isGeneratingSocialImage ? <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div> : <ImageIcon size={16} />}
                                    Materializar Post (Nano Banana Pro)
                                </button>
                            </div>
                        )}
                    </div>

                    {/* RIGHT: Preview */}
                    <div className="flex flex-col items-center">
                        <div className="flex items-center gap-2 mb-4 text-gray-400">
                            <Smartphone size={16} />
                            <span className="text-xs font-mono uppercase">Live Preview</span>
                        </div>

                        {/* Phone Mockup */}
                        <div className="w-[300px] bg-black border-[8px] border-gray-800 rounded-[2.5rem] overflow-hidden shadow-2xl relative min-h-[550px]">
                            {/* Notch */}
                            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-32 h-6 bg-gray-800 rounded-b-xl z-20"></div>
                            
                            {/* Screen Content */}
                            <div className="bg-[#000] h-full flex flex-col text-white pt-8">
                                {/* Header */}
                                <div className="px-4 py-2 flex items-center gap-2 border-b border-gray-800">
                                    <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-cyan-500 to-purple-500"></div>
                                    <div className="text-xs font-bold">Creastilo_Official</div>
                                </div>

                                {/* Image Area */}
                                <div className="aspect-square w-full bg-gray-900 flex items-center justify-center relative overflow-hidden group">
                                    {socialImage ? (
                                        <img src={socialImage} alt="Social Post" className="w-full h-full object-cover animate-in fade-in" />
                                    ) : (
                                        <div className="text-center p-4">
                                            {isGeneratingSocialImage ? (
                                                <div className="flex flex-col items-center gap-2">
                                                    <div className="w-8 h-8 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin"></div>
                                                    <span className="text-[10px] text-cyan-400 font-mono animate-pulse">RENDERING...</span>
                                                </div>
                                            ) : (
                                                <div className="flex flex-col items-center text-gray-700">
                                                    <ImageIcon size={32} />
                                                    <span className="text-[10px] mt-2">Esperando generación...</span>
                                                </div>
                                            )}
                                        </div>
                                    )}
                                    {socialImage && (
                                        <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <a href={socialImage} download="post.png" className="p-2 bg-black/50 text-white rounded-full"><Download size={14}/></a>
                                        </div>
                                    )}
                                </div>

                                {/* Action Bar */}
                                <div className="px-4 py-3 flex gap-4 text-white">
                                    <span className="hover:text-red-500 cursor-pointer">♥</span>
                                    <span>💬</span>
                                    <span>➤</span>
                                </div>

                                {/* Copy Area */}
                                <div className="px-4 pb-8 text-xs space-y-2">
                                    <p className="font-bold">1,248 likes</p>
                                    <p>
                                        <span className="font-bold mr-2">Creastilo_Official</span>
                                        {socialStrategy ? (
                                            <span className="whitespace-pre-wrap">{socialStrategy.copy}</span>
                                        ) : (
                                            <span className="text-gray-600 italic">El copy aparecerá aquí...</span>
                                        )}
                                    </p>
                                    {socialStrategy && (
                                        <p className="text-cyan-500">{socialStrategy.hashtags}</p>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
            )}

            {/* Smart Editor Tool */}
            {activeTool === GenAITool.SmartEditor && (
                <div className="space-y-6 animate-in fade-in h-full flex flex-col pb-4">
                    <div>
                        <h3 className="text-xl font-bold font-display text-green-400 mb-2">Editor Inteligente</h3>
                        <p className="text-sm text-gray-400">Mejora, corrige y expande textos usando modelos Flash (rápidos) y Pro (complejos).</p>
                    </div>

                    <div className="grid lg:grid-cols-2 gap-4 flex-1 min-h-[400px]">
                        {/* Input Column */}
                        <div className="flex flex-col gap-2">
                            <label className="text-xs font-mono text-gray-500 flex justify-between">
                                <span>ENTRADA (TEXTO ORIGINAL)</span>
                                <span className="text-gray-600">{editorInput.length} chars</span>
                            </label>
                            <textarea
                                value={editorInput}
                                onChange={(e) => setEditorInput(e.target.value)}
                                placeholder="Pega aquí tu texto para analizar o mejorar..."
                                className="flex-1 w-full bg-black/30 border border-white/10 rounded-lg p-4 text-gray-200 resize-none focus:border-green-500/50 outline-none text-sm leading-relaxed"
                            />
                        </div>

                        {/* Output Column */}
                        <div className="flex flex-col gap-2">
                            <label className="text-xs font-mono text-gray-500 flex justify-between">
                                <span>RESULTADO</span>
                                {editorOutput && (
                                    <button 
                                        onClick={() => navigator.clipboard.writeText(editorOutput)}
                                        className="flex items-center gap-1 text-green-400 hover:text-white cursor-pointer"
                                    >
                                        <Copy size={12} /> Copiar
                                    </button>
                                )}
                            </label>
                            <div className="flex-1 w-full bg-gradient-to-br from-black/40 to-green-900/10 border border-white/10 rounded-lg p-4 text-white resize-none relative overflow-y-auto">
                                {isEditing ? (
                                    <div className="absolute inset-0 flex items-center justify-center bg-black/50 backdrop-blur-sm z-10">
                                        <div className="flex flex-col items-center">
                                            <RefreshCw className="animate-spin text-green-400 mb-2" size={32} />
                                            <span className="text-xs font-mono text-green-200 animate-pulse">PROCESANDO...</span>
                                        </div>
                                    </div>
                                ) : editorOutput ? (
                                    <p className="whitespace-pre-wrap text-sm leading-relaxed">{editorOutput}</p>
                                ) : (
                                    <div className="flex flex-col items-center justify-center h-full text-gray-700 opacity-50">
                                        <ArrowRight size={32} className="mb-2" />
                                        <span className="italic text-xs font-mono">El resultado aparecerá aquí</span>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    {/* Actions Toolbar */}
                    <div className="bg-white/5 border border-white/5 rounded-xl p-4">
                        <div className="flex flex-wrap items-center gap-4">
                            <div className="flex items-center gap-2 border-r border-white/10 pr-4">
                                <Zap size={16} className="text-yellow-400" />
                                <span className="text-xs font-bold text-gray-400">RÁPIDO (FLASH)</span>
                            </div>
                            
                            <button 
                                onClick={() => handleSmartEdit("Corrige la gramática y ortografía. Mantén el tono original.", 'basic')}
                                disabled={isEditing || !editorInput}
                                className="px-3 py-1.5 bg-white/5 hover:bg-white/10 text-gray-300 text-xs rounded border border-white/10 transition-colors"
                            >
                                Corregir Gramática
                            </button>
                            <button 
                                onClick={() => handleSmartEdit("Resume el texto en 3 puntos clave.", 'basic')}
                                disabled={isEditing || !editorInput}
                                className="px-3 py-1.5 bg-white/5 hover:bg-white/10 text-gray-300 text-xs rounded border border-white/10 transition-colors"
                            >
                                Resumir
                            </button>
                            <button 
                                onClick={() => handleSmartEdit("Reescribe el texto con un tono más profesional, corporativo y persuasivo.", 'basic')}
                                disabled={isEditing || !editorInput}
                                className="px-3 py-1.5 bg-white/5 hover:bg-white/10 text-gray-300 text-xs rounded border border-white/10 transition-colors"
                            >
                                Tono Profesional
                            </button>
                        </div>

                        <div className="w-full h-px bg-white/5 my-3"></div>

                        <div className="flex flex-wrap items-center gap-4">
                            <div className="flex items-center gap-2 border-r border-white/10 pr-4">
                                <BrainCircuit size={16} className="text-purple-400" />
                                <span className="text-xs font-bold text-gray-400">COMPLEJO (PRO)</span>
                            </div>
                            
                            <button 
                                onClick={() => handleSmartEdit("Realiza un análisis profundo del texto. Identifica el tono, la intención, y sugiere 3 mejoras críticas para aumentar el impacto.", 'complex')}
                                disabled={isEditing || !editorInput}
                                className="px-4 py-1.5 bg-gradient-to-r from-purple-900/50 to-pink-900/50 hover:from-purple-900/70 hover:to-pink-900/70 text-purple-200 text-xs rounded border border-purple-500/30 transition-all flex items-center gap-2 group"
                            >
                                <Sparkles size={12} className="group-hover:rotate-12 transition-transform" /> Análisis Profundo
                            </button>
                            <button 
                                onClick={() => handleSmartEdit("Expande estas ideas añadiendo contexto, ejemplos relevantes y argumentos sólidos. Hazlo más detallado.", 'complex')}
                                disabled={isEditing || !editorInput}
                                className="px-4 py-1.5 bg-gradient-to-r from-purple-900/50 to-pink-900/50 hover:from-purple-900/70 hover:to-pink-900/70 text-purple-200 text-xs rounded border border-purple-500/30 transition-all flex items-center gap-2"
                            >
                                <Layers size={12} /> Expandir Creativamente
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Image Synth Tool */}
            {activeTool === GenAITool.ImageSynth && (
              <div className="space-y-6 animate-in fade-in pb-10">
                <div className="flex justify-between items-start">
                    <div>
                        <h3 className="text-xl font-bold font-display text-purple-400 mb-2">Optimizador Visual</h3>
                        <p className="text-sm text-gray-400">Convierte ideas básicas en Prompts profesionales para Midjourney v6.</p>
                    </div>
                    <div className="bg-white/5 border border-white/10 rounded-lg p-2 flex items-center gap-2">
                        <Layers size={14} className="text-purple-400" />
                        <select 
                            value={imageStyle}
                            onChange={(e) => setImageStyle(e.target.value)}
                            className="bg-transparent text-xs text-white outline-none border-none cursor-pointer font-mono"
                        >
                            <option value="Cinematic">Cinemático</option>
                            <option value="Anime">Anime (Niji)</option>
                            <option value="3D Render">3D Octane Render</option>
                            <option value="Oil Painting">Pintura al Óleo</option>
                            <option value="Cyberpunk">Cyberpunk</option>
                            <option value="Minimalist">Minimalista</option>
                        </select>
                    </div>
                </div>

                 <div className="space-y-2">
                  <label className="text-xs font-mono text-gray-500">CONCEPTO BÁSICO</label>
                  <div className="flex gap-2">
                    <input 
                      type="text" 
                      value={imagePrompt}
                      onChange={(e) => setImagePrompt(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && enhancePrompt()}
                      placeholder="Ej. Gato astronauta mirando la tierra..."
                      className="flex-1 bg-black/30 border border-white/10 rounded-lg px-4 py-3 text-white focus:border-purple-400 outline-none"
                    />
                    <button 
                      onClick={enhancePrompt}
                      disabled={isGenerating || !imagePrompt}
                      className="px-6 bg-purple-500/20 text-purple-400 border border-purple-500/50 rounded-lg hover:bg-purple-500/30 disabled:opacity-50 font-bold flex items-center gap-2"
                    >
                      {isGenerating ? <div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"></div> : <Wand2 size={16}/>}
                      Optimizar
                    </button>
                  </div>
                </div>

                {/* Configuration Row for Generation */}
                <div className="bg-white/5 border border-white/5 rounded-xl p-4 flex flex-wrap items-center justify-between gap-4">
                    <div className="flex items-center gap-4">
                        <div className="flex items-center gap-2 text-purple-300 border-r border-white/10 pr-4">
                            <Settings2 size={18} />
                            <span className="text-xs font-bold font-mono">CONFIG</span>
                        </div>
                        
                        <div className="space-y-1">
                            <label className="text-[10px] uppercase text-gray-500 font-mono block">Aspecto</label>
                            <select 
                                value={aspectRatio}
                                onChange={(e) => setAspectRatio(e.target.value)}
                                className="bg-black/40 border border-white/10 rounded px-2 py-1 text-xs text-white outline-none focus:border-purple-500 min-w-[80px]"
                            >
                                {['1:1', '2:3', '3:2', '3:4', '4:3', '9:16', '16:9', '21:9'].map(r => (
                                    <option key={r} value={r}>{r}</option>
                                ))}
                            </select>
                        </div>
                        
                        <div className="space-y-1">
                            <label className="text-[10px] uppercase text-gray-500 font-mono block">Calidad</label>
                            <select 
                                value={imageSize}
                                onChange={(e) => setImageSize(e.target.value)}
                                className="bg-black/40 border border-white/10 rounded px-2 py-1 text-xs text-white outline-none focus:border-purple-500 min-w-[80px]"
                            >
                                {['1K', '2K', '4K'].map(s => (
                                    <option key={s} value={s}>{s}</option>
                                ))}
                            </select>
                        </div>
                    </div>
                    
                    <button
                        onClick={handleGenerateImage}
                        disabled={isGeneratingImage || (!imagePrompt && !enhancedPrompt)}
                        className="px-6 py-2 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-bold hover:shadow-[0_0_20px_rgba(168,85,247,0.4)] transition-all flex items-center gap-2 disabled:opacity-50 text-sm"
                    >
                        {isGeneratingImage ? <div className="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full"></div> : <ImageIcon size={16} />}
                        Generar Imagen
                    </button>
                </div>

                {generatedImage && (
                    <div className="mt-6 rounded-xl overflow-hidden border border-white/10 relative group bg-black/50 shadow-2xl animate-in zoom-in-95 duration-500">
                        <img src={generatedImage} alt="Generada por IA" className="w-full h-auto object-contain max-h-[500px]" />
                        <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                            <a href={generatedImage} download={`creastilo-gen-${Date.now()}.png`} className="p-3 bg-black/60 text-white rounded-lg hover:bg-black/80 border border-white/20 block">
                                <Download size={20} />
                            </a>
                        </div>
                        <div className="absolute bottom-4 left-4 bg-black/60 px-3 py-1 rounded-full border border-white/10 backdrop-blur-sm">
                            <span className="text-[10px] font-mono text-purple-300">GEMINI NANO PRO • {aspectRatio} • {imageSize}</span>
                        </div>
                    </div>
                )}

                {enhancedPrompt && (
                    <div className="grid lg:grid-cols-2 gap-6 animate-in slide-in-from-bottom-4">
                        {/* Result Column */}
                        <div className="bg-gradient-to-br from-purple-900/20 to-black border border-purple-500/30 rounded-lg p-6 flex flex-col">
                            <p className="text-xs font-mono text-purple-300 mb-4 flex items-center gap-2">
                                <Zap size={12} /> PROMPT OPTIMIZADO
                            </p>
                            <p className="text-sm text-white font-medium whitespace-pre-wrap leading-relaxed flex-1">{enhancedPrompt}</p>
                            <div className="mt-4 pt-4 border-t border-white/5 flex justify-end">
                                <button className="text-xs text-gray-400 hover:text-white flex items-center gap-1" onClick={() => navigator.clipboard.writeText(enhancedPrompt)}>
                                    <Copy size={12} /> Copiar
                                </button>
                            </div>
                        </div>

                        {/* Analysis Column (Areas of Opportunity) */}
                        {promptAnalysis && (
                            <div className="bg-black/40 border border-white/10 rounded-lg p-6 relative overflow-hidden group">
                                <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                                    <ScanEye size={100} className="text-purple-500" />
                                </div>
                                
                                <h4 className="text-xs font-mono text-gray-400 mb-6 uppercase tracking-widest border-b border-white/5 pb-2">Diagnóstico de Prompt</h4>
                                
                                <div className="flex items-center gap-6 mb-6">
                                    <div className="relative w-16 h-16 flex items-center justify-center">
                                        <svg className="w-full h-full transform -rotate-90">
                                            <circle cx="32" cy="32" r="28" stroke="currentColor" strokeWidth="4" fill="transparent" className="text-gray-800" />
                                            <circle cx="32" cy="32" r="28" stroke="currentColor" strokeWidth="4" fill="transparent" 
                                                className={`${promptAnalysis.score > 70 ? 'text-green-500' : promptAnalysis.score > 40 ? 'text-yellow-500' : 'text-red-500'}`}
                                                strokeDasharray={175}
                                                strokeDashoffset={175 - (175 * promptAnalysis.score) / 100}
                                            />
                                        </svg>
                                        <span className="absolute text-sm font-bold text-white">{promptAnalysis.score}</span>
                                    </div>
                                    <div className="flex-1">
                                        <p className="text-sm text-gray-300 italic">"{promptAnalysis.feedback}"</p>
                                    </div>
                                </div>

                                <div className="space-y-4">
                                    <div>
                                        <p className="text-xs text-red-400 font-bold mb-2 flex items-center gap-1"><AlertCircle size={12} /> ELEMENTOS FALTANTES</p>
                                        <div className="flex flex-wrap gap-2">
                                            {promptAnalysis.missing_elements?.map((item: string, i: number) => (
                                                <span key={i} className="text-[10px] px-2 py-1 rounded bg-red-500/10 text-red-300 border border-red-500/20">{item}</span>
                                            ))}
                                        </div>
                                    </div>
                                    
                                    <div>
                                        <p className="text-xs text-green-400 font-bold mb-2 flex items-center gap-1"><CheckCircle2 size={12} /> TÉCNICAS APLICADAS</p>
                                        <div className="flex flex-wrap gap-2">
                                            {promptAnalysis.applied_techniques?.map((item: string, i: number) => (
                                                <span key={i} className="text-[10px] px-2 py-1 rounded bg-green-500/10 text-green-300 border border-green-500/20">{item}</span>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                )}
              </div>
            )}

            {/* Voice Tool */}
            {activeTool === GenAITool.Voice && (
                <div className="space-y-6 animate-in fade-in">
                    <div>
                        <h3 className="text-xl font-bold font-display text-pink-400 mb-2">Clonación de Voz</h3>
                        <p className="text-sm text-gray-400">Convierte texto a voz futurista al instante.</p>
                    </div>

                    <div className="bg-black/20 border border-pink-500/20 rounded-xl p-6 relative overflow-hidden">
                         <div className="absolute top-0 right-0 w-32 h-32 bg-pink-500/10 rounded-full blur-2xl -z-10"></div>
                         
                         <textarea
                            value={textToSpeechInput}
                            onChange={(e) => setTextToSpeechInput(e.target.value)}
                            placeholder="Escribe algo para que la IA lo diga..."
                            className="w-full bg-black/40 border border-white/10 rounded-lg p-4 text-white resize-none h-32 mb-4 focus:border-pink-500 outline-none font-mono text-sm"
                         />

                         <div className="flex gap-4">
                             <button 
                                onClick={() => handleSpeak(textToSpeechInput)}
                                disabled={!textToSpeechInput}
                                className="flex items-center gap-2 px-6 py-3 bg-pink-500/20 text-pink-400 border border-pink-500/50 rounded-lg hover:bg-pink-500/30 transition-all disabled:opacity-50 font-bold"
                             >
                                <Play size={18} fill="currentColor" /> Sintetizar
                             </button>
                             
                             <button 
                                onClick={handleStopSpeak}
                                className="flex items-center gap-2 px-6 py-3 border border-white/10 text-gray-400 rounded-lg hover:bg-white/5 transition-all"
                             >
                                <Square size={18} fill="currentColor" /> Detener
                             </button>
                         </div>
                    </div>

                    <div className="h-24 flex items-end justify-center gap-1 opacity-50">
                        {[...Array(30)].map((_, i) => (
                            <div 
                                key={i} 
                                className={`w-1.5 bg-pink-500 rounded-t-sm transition-all duration-100 ${isSpeaking ? 'animate-pulse' : ''}`}
                                style={{ 
                                    height: isSpeaking ? `${Math.random() * 100}%` : '10%',
                                    animationDelay: `${i * 0.05}s`
                                }}
                            ></div>
                        ))}
                    </div>
                </div>
            )}
          </div>
        </div>
    </div>
  );
};

export default GenAIStudio;
